#!/bin/bash
#
# Install a full clamav
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/clamav
USAGE="usage: $0"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Move the actual files into place
rm -rf $DEST_DIR/* || error_exit "Cannot remove contents of $DEST_DIR"
mkdir -p $DEST_DIR || error_exit "Cannot create $DEST_DIR"
cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Cannot install to $DEST_DIR"
rm -f $DEST_DIR/$PROGNAME

# Symlink all the bins and sbins
for BIN in clamav-config clambc clamconf clamdscan clamdtop clamscan clamsubmit freshclam sigtool; do
  ln -sf $DEST_DIR/bin/$BIN /usr/bin || error_exit "Cannot link $BIN to /usr/bin"
done
for SBIN in clamav-milter clamd; do
  ln -sf $DEST_DIR/sbin/$BIN /usr/sbin || error_exit "Cannot link $SBIN to /usr/sbin"
done
for INIT in clamd freshclam; do
  ln -sf $DEST_DIR/init.d/$INIT /etc/init.d || error_exit "Cannot link $INIT to /etc/init.d"
done
ln -sf $DEST_DIR/etc /etc/clamav || error_exit "Cannot link etc to /etc/clamav"

exit 0
