#!/bin/bash
#
# Perform necessary clamav setup steps
# before package is installed.
#

PROGNAME=`basename $0`

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

getent passwd clamav &> /dev/null || useradd -r clamav || error_exit "Cannot create clamav user"

echo "You're about to install clamav!"
